// motivationModel.js
export const quotes = [
    "The only way to do great work is to love what you do.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Believe you can and you're halfway there.",
  "Don't watch the clock; do what it does. Keep going.",
  "Everything you've ever wanted is on the other side of fear.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "It's not whether you get knocked down, it's whether you get up.",
  "If you're going through hell, keep going.",
  "Setting goals is the first step in turning the invisible into the visible.",
  "You are never too old to set another goal or to dream a new dream.",
  "Quality is not an act, it is a habit.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Do what you can, with what you have, where you are.",
  "The best way to predict the future is to create it.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "The secret of getting ahead is getting started.",
  "Your time is limited, don't waste it living someone else's life.",
  "Strive not to be a success, but rather to be of value.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "The only person you are destined to become is the person you decide to be.",
  "Go confidently in the direction of your dreams. Live the life you have imagined.",
  "When you reach the end of your rope, tie a knot in it and hang on.",
  "The best revenge is massive success.",
  "Don't count the days, make the days count.",
  "You miss 100% of the shots you don't take.",
  "The purpose of our lives is to be happy.",
  "Life is 10% what happens to us and 90% how we react to it.",
  "The mind is everything. What you think you become.",
  "Change your thoughts and you change your world.",
  "Either you run the day or the day runs you.",
  "Whatever the mind can conceive and believe, it can achieve.",
  "The only impossible journey is the one you never begin.",
  "What we achieve inwardly will change outer reality.",
  "You can't build a reputation on what you are going to do.",
  "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.",
  "The only true wisdom is in knowing you know nothing.",
  "We become what we think about most of the time.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "What you lack in talent can be made up with desire, hustle and giving 110% all the time.",
  "Do what you can, where you are, with what you have.",
  "The journey of a thousand miles begins with one step.",
  "The only thing standing between you and your goal is the story you keep telling yourself.",
  "If there is no struggle, there is no progress.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Success is liking yourself, liking what you do, and liking how you do it.",
  "Opportunities don't happen. You create them.",
  "If you want to lift yourself up, lift up someone else.",
  "The way to get started is to quit talking and begin doing.",
  "You can't use up creativity. The more you use, the more you have.",
  "You are the master of your destiny. You can influence, direct and control your own environment.",
  "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",
  "If you don't design your own life plan, chances are you'll fall into someone else's plan.",
  "Don't judge each day by the harvest you reap but by the seeds that you plant.",
  "Nothing will work unless you do.",
  "You must be the change you wish to see in the world.",
  "Aim for the moon. If you miss, you may hit a star.",
  "It is never too late to be what you might have been.",
  "Start where you are. Use what you have. Do what you can.",
  "The question isn't who is going to let me; it's who is going to stop me.",
  "The most difficult thing is the decision to act, the rest is merely tenacity.",
  "Believe and act as if it were impossible to fail.",
  "Don't be afraid to give up the good to go for the great.",
  "The only way to do great work is to love what you do.",
  "In the middle of difficulty lies opportunity.",
  "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did do.",
  "Fall seven times and stand up eight.",
  "The most common way people give up their power is by thinking they don't have any.",
  "Life is what happens when you're busy making other plans.",
  "If you look at what you have in life, you'll always have more.",
  "What we fear doing most is usually what we most need to do.",
  "Don't let yesterday take up too much of today.",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
  "The man who has confidence in himself gains the confidence of others.",
  "If you want to make your dreams come true, the first thing you have to do is wake up.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "Every strike brings me closer to the next home run.",
  "Don't let what you cannot do interfere with what you can do.",
  "The successful warrior is the average man, with laser-like focus.",
  "What's the point of being alive if you don't at least try to do something remarkable?",
  "In the end, we only regret the chances we didn't take.",
  "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.",
  "Life shrinks or expands in proportion to one's courage.",
  "Too many of us are not living our dreams because we are living our fears.",
  "If you want something you've never had, you must be willing to do something you've never done.",
  "Courage is resistance to fear, mastery of fear, not absence of fear.",
  "There is no passion to be found playing small—in settling for a life that is less than the one you are capable of living.",
  "We may encounter many defeats but we must not be defeated.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Keep your eyes on the stars, and your feet on the ground.",
  "Life is either a daring adventure or nothing at all.",
  "In the end, it's not the years in your life that count. It's the life in your years.",
  "The two most important days in your life are the day you are born and the day you find out why.",
  "The best way to predict your future is to create it.",
  "The only person who is educated is the one who has learned how to learn and change.",
  "A successful man is one who can lay a firm foundation with the bricks others have thrown at him."
];

